### ISSUE TITLE
How much memory did you use

### ISSUE THREAD

**Issue by sandangel** [theburningmonk/lambda-platform-perf-comparison#2]
I'm trying to add golang for comparison but you not specific your lambda function configuration. Could you please add a configuration in README.md

**Comment by theburningmonk** [comment]
are you using the Serverless framework? in each of the folders you'll find a `serverless.yml` file that specifies the function, and if you don't explicitly set the memory then it defaults to 1024MB.

have a look at this https://github.com/eawsy/aws-lambda-go-shim it lets you use Go with the Serverless framework

**Comment by sandangel** [comment]
Oh, I got it. My test is with 512 Mb memory and I reused all your example for others function as well as artillery for testing. Here is the chart.
![image](https://user-images.githubusercontent.com/22189661/27468077-907dbdee-5822-11e7-9b74-53d6bc20d522.png)

Java seem to be the most unstable performance.
